[package]
name = "bar_control"
version = "0.1.1"
authors = ["UndeadLeech <programming@undeadleech.de>"]

[dependencies]
serde_derive = "0.9.11"
libudev = "0.2.0"
serde = "0.9.11"
time = "0.1.36"
rand = "0.3.15"
regex = "0.2.1"
i3ipc = "0.4.2"
toml = "0.3.1"
