[package]
name = "bar_control"
version = "0.1.0"
authors = ["UndeadLeech <programming@undeadleech.de>"]

[dependencies]
toml = "0.2"
time = "0.1"
rand = "0.3"
regex = "0.1"
i3ipc = "0.4"
libudev = "0.2"
